version: "3"
services:
  db_postgres:
    image: postgres:13
    container_name: db_postgres
    restart: always
    ports:
      - 2345:5432
    env_file:
      - back-end/.env
    volumes:
      - db_postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_postgres
    env_file:
      - back-end/.env

  app_react:
    build: ./front-end
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react
      - db_postgres
      - node_app

volumes:
  db_postgres:
  build_react:
